# Generated by Django 5.0.2 on 2024-02-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='doctors_picture/')),
                ('city', models.CharField(max_length=50)),
                ('msn', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='service_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Klinik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Klinik', to='service_app.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='expertise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='service_app.proficiency'),
        ),
    ]
